services:
  spring:
    # build: '../server'
    image: mkopczewski/zespolowe:latest
    ports:
      - "8080:8080"
    volumes:
      - "/home/mdomino/zespolowe-volume:/app/data"

    env_file:
      - ../server/.env
    environment:
      DEVICES_JSON_FILEPATH: /app/data/devices.json
      USERS_FILEPATH: /app/data/users.txt