services:
  spring:
    image: mkopczewski/zespolowe:latest
    ports:
      - "8080:8080"
    volumes:
      - "<Ścieżka do folderu plików konfiguracyjnych>:/app/data"
      - "<Ścieżka do folderu w którym chcemy zapisać nagrania z kamer>:/app/data/media/"

    env_file:
      - .env-server
    environment:
      DEVICES_JSON_FILEPATH: /app/data/devices.json
      USERS_FILEPATH: /app/data/users.txt
      MEDIA_FOLDER: /app/data/

  app:
    image: my-nextjs-app:latest
    env_file:
      - .env-front
    ports:
      - "3000:3000"
    volumes:
      - .:/app


