### TODO: Rozbudowac to w przyszlosci

name: Front-end CICD

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    container:
      image: node:23-alpine3.20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Build without Tests
        working-directory: ./web_app
        run: |
          npm install
          npm run build

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Build custom test image
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./web_app
          file: ./web_app/Dockerfile
          load: true
          tags: front-test-image:latest
          build-args: |
            AGENT_UID=${{ github.run_id }}
            AGENT_GID=1000

      - name: Run Tests in Container
        working-directory: ./web_app
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace front-test-image:latest npm run test

  docker-build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main'

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Log in to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # TODO: DODAC W PROJEKCIE PRINT WERSJI
      - name: Get Version and Commit Hash
        id: vars
        run: |
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        working-directory: ./web_app
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./web_app
          file: ./web_app/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/s_cameras_front:${{ env.VERSION }}.${{ env.COMMIT }}
            ${{ env.DOCKERHUB_USERNAME }}/s_cameras_front:latest
