apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nextapp.secrets.name }}
type: {{ .Values.nextapp.secrets.type }}
data:
  GITHUB_CLIENT_ID: {{ .Values.nextapp.clientid | b64enc }}
  GITHUB_CLIENT_SECRET: {{ .Values.nextapp.clientsecret | b64enc }}
  NEXTAUTH_SECRET: {{ .Values.nextapp.nextauthsecret | b64enc }}
